org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dkotlin.daemon.dir=E:\YINGYU\YINGYU\dev-cache\kotlin-daemon
systemProp.kotlin.daemon.dir=E:\YINGYU\YINGYU\dev-cache\kotlin-daemon
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
