// 本文件由脚本生成（源：2023-2026四川专升本大学英语真题汇编（无答案）.docx）。
// 官方答案缺失：所有客观题 answerIdx 均为 -1，载入预设后由「AI 补参考答案」流程填充。
// ignore_for_file: lines_longer_than_80_chars

import 'models.dart';

/// 综合模拟套卷的真题预设：用户可选择某一年的真题直接作答，
/// 也可以选择 AI 生成（生成规则同样锚定这四年真题的题型与考查侧重点）。
class RealExamPreset {
  final String year;
  final String title;
  final String summary;
  /// 每次调用返回全新实例，避免多轮考试之间共享可变状态
  final FullExamPaper Function() build;
  /// 该卷缺失大题的 AI 补全主题提示（key = 需要补全的大题）
  final Map<ExamSection, String> fillHints;

  const RealExamPreset({
    required this.year,
    required this.title,
    required this.summary,
    required this.build,
    this.fillHints = const {},
  });
}

/// 按年份取真题预设
RealExamPreset? presetOfYear(String year) {
  for (final p in kRealExamPresets) {
    if (p.year == year) return p;
  }
  return null;
}

const List<RealExamPreset> kRealExamPresets = [
  RealExamPreset(
    year: '2023',
    title: '2023 年真题',
    summary: "完整真题 · 100分 · 75题（官方无答案，由 AI 补参考答案）",
    build: _buildPaper2023,
    fillHints: {
        ExamSection.vocab: "【同卷已存题干（仿其难度与考点，不要重复出题）】\n1. I am leaving in ____ minute; in ____ fact, I'll leave when I turn off the lights.\n2. Please turn to page ____, look at the ____ picture.\n3. The kids learned that light ____ faster than sound.\n4. The photo exhibition was held to ____ the environmental awareness.\n5. The greatest lawyer made a speech ____ education law.\n6. —We need a drink. —____! Let's have one.\n7. Neither you nor I am expert on this issue, ____?\n8. The hall was named after the professor ____ made great contributions to the university.\n9. Hardly had I put down my cell phone ____ it ran again.\n10. Peter won the first prize of the speech competition, and he ____ have studied very hard.\n11. The AI engineer, as well as his team members, ____ to attend the seminar on ChatGPT last month.\n12. The teacher explained it again ____ he could make himself better understood.\n13. The ____ of blood always makes him frightened.\n14. As we arrived too early, ____ of the rooms were ready.\n15. When he was a child, the scientist was ____ about how life on earth began.\n16. —Have you completed your report yet? —No, but I ____ on it all day yesterday.\n17. ____ I know, they will go to Chengdu to watch the World University Games this summer.\n18. Never in my life ____ such a wonderful lion dance.\n19. The school ____ great importance to students' mental health.\n20. They were ____ in the middle of their telephone conversation.\n21. ____ it was only 5 p.m., the street lights in this northeast city were already on.\n22. They gave a(n) ____ broadcast while the talent show was going on.\n23. Lily has made an ____ to meet his science teacher next Monday.\n24. It's high time you ____ smoking.\n25. Weather ____, they'll go to visit the Panda Base.\n26. The manager had assistant ____ a presentation for the meeting with the clients.\n27. ____ see the lost cat will get a gift as a reward.\n28. We were excited to learn Prof. Tu Youyou became the ____ scientist who won the Nobel Prize.\n29. I'd like to take ____ of this opportunity to thank you for your support.\n30. Travelling is becoming ____ popular in China as more and more people have their own cars.",
      },
  ),
  RealExamPreset(
    year: '2024',
    title: '2024 年真题',
    summary: "回忆版 · 150分 · 77题 · 缺阅读/完形/对话/选词/翻译，AI 按真题主题补全",
    build: _buildPaper2024,
    fillHints: {
        ExamSection.vocab: "这是2024年四川专升本真题「词汇与语法结构」第16—20题（原卷该部分回忆缺失）。请严格仿照同卷第1—15题的难度、句型与考点（冠词、情态动词推测、反义疑问、主谓一致、虚拟语气、非谓语动词、定语从句、名词性从句、副词与名词词义辨析、固定搭配）续出5题。\n【同卷已存题干（仿其难度与考点，不要重复出题）】\n1. Chengdu is ____ beautiful city and ____ capital of Sichuan Province.\n2. They ____ be at home, for there is no light in the room.\n3. The new movie directed by Jia Ling is quite inspiring, ____?\n4. The professor, along with his assistants, ____ on the project day and night to meet the deadline.\n5. The president ordered that all exits ____ kept clear in case of fire.\n6. I'd like to study civil engineering in university, ____ my cousin prefers computer science.\n7. A college in Sichuan announced a spring break yesterday, ____ caused a heated discussion among students.\n8. News comes ____ video can be easily made with the AI tool.\n9. Tracy appreciated ____ the opportunity to visit China through the summer camp program.\n10. Jack has been living in Beijing for years, ____, he speaks Chinese quite fluently.\n11. It is necessary to look into the case ____ you take any action.\n12. I can't thank you ____ much for your help. Without it, I couldn't have completed this task on time.\n13. A good team leader has to know the ____ and weakness of the member and create a harmonious environment for work.\n14. —Volunteering is becoming ____ popular in China. —Yeah, people are now aware that helping others is helping themselves.\n15. What's the ____ of helping him if he does not want to make any effort himself?",
        ExamSection.reading: "这是2024年四川专升本真题「阅读理解」4篇（原文回忆缺失）。据考生回忆，四篇主题依次为：①因迟到冒犯他人后写信道歉解释；②拯救一只天鹅并与之成为朋友的故事；③年轻人对待副业（side jobs）的不同态度；④神舟飞船上的太空实验（\"浮力消失\"\"水球\"等物理现象）。请按这4个主题还原短文，每篇配4道选择题。",
        ExamSection.cloze: "这是2024年四川专升本真题「完形填空」20空（各空选项回忆缺失）。主题为丝绸之路（The Silk Road）：贸易路线与长度、丝绸、古罗马、印度中间商、商队、沙漠高山与沙暴、中世纪衰落与新航路开辟。请据此出题。\n【真题原文（请在这篇原文上挖 20 个空出题，尽量保持原文用词）】\nThe Silk Road is a name given to the many trade routes that connected Europe and the Mediterranean (地中海) with the Asian world. The route is over 6,500 km long and got its name because the early Chinese traded silk along it. Although silk was the main trading item, there were many other goods that travelled along the Silk Road between Eastern Asia and Europe. In the course of time, medicine, perfumes, spices and livestock (家畜) found their way between continents.\n\nThe Chinese learned to make silk thousands of years ago. For a long time they were the only ones who knew how to make this precious material. Only the emperor, his family and his highest advisers were allowed to wear clothes made of silk. For a long time the Chinese guarded this secret very carefully. The ancient Romans were the first Europeans who became aware of this wonderful material. Trading started, often with Indians as middlemen (中间人) who traded silk with the Chinese in exchange for gold and silver which they got from the Romans.\n\nTravelling along the route was dangerous. The hot desert, high mountains and sandstorms made traveling a rough business. Most of the goods along the Silk Road were carried by caravans (商队). Traders sometimes brought goods from one destination on the Silk Road to another, from where the goods would be transported by someone else. Over the centuries people settled along the ancient route and many cities emerged. Later on there were fewer hardships to overcome, but by no means was it easy.\n\nIn the early Middle Ages, traffic along the route decreased because of the decline of the Roman Empire. Trading along the Silk Road became stronger again between the 13th and 14th centuries, when the Mongols controlled central Asia. During the Age of Exploration the Silk Road lost its importance because new sea routes to Asia were discovered.",
        ExamSection.dialogue: "2024年真题「补全对话」回忆缺失。请按四川专升本难度出一组7选5（5空，2分/空）的日常交际对话。",
        ExamSection.bankedCloze: "2024年真题「选词填空」回忆缺失。请出一篇15选10（10空，1分/空）的通用类短文。",
        ExamSection.en2zh5: "2024年真题「英译汉」原文缺失，翻译主题为\"静谧时刻的价值（the value of quiet moments）\"。请出5个英文句子并给出中文参考译文。",
      },
  ),
  RealExamPreset(
    year: '2025',
    title: '2025 年真题',
    summary: "回忆版 · 150分 · 77题 · 仅存6道词汇与作文线索，其余 AI 按真题主题补全",
    build: _buildPaper2025,
    fillHints: {
        ExamSection.vocab: "这是2025年四川专升本真题「词汇与语法结构」第7—20题（原卷该部分回忆缺失）。请严格仿照同卷第1—6题的风格与考点（冠词、不定代词、主谓一致与时态、情态动词表推测、被动语态、wish 虚拟语气）续出14题。\n【同卷已存题干（仿其难度与考点，不要重复出题）】\n1. Henry likes to play ____ piano, while his brother prefers playing ____ football.\n2. We invited Linda and Cathy to dinner, but ____ of them came.\n3. The number of new energy vehicles in our country ____ a lot in recent years.\n4. —Juicy graduated from college at a very young age. —She ____ have been a smart student.\n5. She wondered what effective measures ____ to increase the productivity.\n6. —Have you ever been to Beijing? —No, I wish I ____.",
        ExamSection.reading: "这是2025年四川专升本真题「阅读理解」4篇（原文回忆缺失）。请按四川专升本常考话题（校园生活、志愿服务、人工智能与科技、传统文化/非遗、健康生活）各出1篇，每篇配4道选择题。",
        ExamSection.cloze: "2025年真题「完形填空」20空回忆缺失。请出一篇校园成长 / 亲情感悟类记叙文。",
        ExamSection.dialogue: "2025年真题「补全对话」回忆缺失。请出一组7选5（5空，2分/空）的日常交际对话。",
        ExamSection.bankedCloze: "2025年真题「选词填空」回忆缺失，主题与\"读书、父亲\"相关。请据此出15选10（10空，1分/空）。",
        ExamSection.en2zh5: "2025年真题「英译汉」原文缺失，翻译主题为\"陌生人留言鼓励\"。请出5个英文句子并给出中文参考译文。",
        ExamSection.writing: "2025年真题「短文写作」回忆缺失。请按四川专升本常考应用文（建议信/邀请信/告知信/通知）出一道25分写作题（不少于120词），并给出英文参考范文。",
      },
  ),
  RealExamPreset(
    year: '2026',
    title: '2026 年真题',
    summary: "回忆版 · 150分 · 75题 · 缺 Passage 4/选词/翻译，AI 补全",
    build: _buildPaper2026,
    fillHints: {
        ExamSection.reading: "这是2026年四川专升本真题 Passage 4（原文回忆缺失）。同卷前三篇分别为：①澳大利亚农场主在油菜花田用飞机求婚的记叙文；②中学生Bob在咖啡馆做兼职的成长经历；③中国AutoFlight公司 eVTOL 飞行汽车 Matrix 的试飞演示。请补1篇同难度、同体裁的短文，配4道选择题。",
        ExamSection.bankedCloze: "2026年真题「选词填空」原文与选项缺失，主题为多伦多研究者的观鸟（birdwatching）与大脑健康研究。请据此出15选10（10空，1分/空）。\n【真题原文片段（请据此补全整篇）】\nBirds are fascinating and beautiful creatures. Looking at them in the wild can be good for us. That is what researchers in Toronto, Canada, say. The scientists found that birdwatching could  62  our brains against age-related diseases. Lead researcher Dr. Erik Wing said: \"Skills from birding could be  63  for intelligence and thinking.\" ... Dr. Wing and his colleagues compared scans of the brain activity of 29 veteran birdwatchers and 29 newbies. The brains of the veteran birders were a lot more active. Dr. Wing said the veterans had a longer ...",
        ExamSection.en2zh5: "2026年真题「英译汉」原文缺失，翻译主题为\"亲情与陪伴\"。请出5个英文句子并给出中文参考译文。",
        ExamSection.vocab: "【同卷已存题干（仿其难度与考点，不要重复出题）】\n1. The price of petrol has become ____ major concern of ____ society.\n2. Could you please tell me ____ we get to the Sanxingdui Museum?\n3. Jack, as well as his two children, ____ for China this afternoon.\n4. Chengdu, ____ for its rich cultural heritage and delicious local food, has become a top choice for travelers around the world.\n5. —Peter had a wonderful party yesterday. —____.\n6. The Dujiangyan Irrigation System is still in use ____ it was built over 2000 years ago.\n7. A lot of progress has been made in the 14th ____ Plan period.\n8. The new washing machine uses ____ water and electricity than the old one.\n9. Many people find ____ enjoyable to travel in western Sichuan.\n10. —The last man ____ pays for the meal. —Good idea!\n11. The Giant Panda Base ____ we visited last week is popular with foreign tourists.\n12. He never said he was good at singing, ____?\n13. The teacher said practice ____ perfect, so we should keep working hard.\n14. He couldn't fall asleep with all that noise ____.\n15. It is necessary that measures ____ to further develop vocational education.\n16. Vivian has a lot of problems with her life, but she does not know whom to ____.\n17. It is very ____ of you to help me with Chinese learning.\n18. You ____ finish the project before the deadline, or you will face serious consequences.\n19. Carelessness was the main ____ of the accident in the lab.\n20. If it rains tomorrow, we will ____ the sports meeting till next week.",
      },
  ),
];

FullExamPaper _buildPaper2023() {
  return FullExamPaper(
    title: '四川专升本大学英语 2023 年真题',
    totalTimeMin: 120,
    isRealPaper: true,
    realYear: '2023',
    sectionCounts: {ExamSection.vocab: 30, ExamSection.reading: 20, ExamSection.cloze: 20, ExamSection.en2zh5: 4, ExamSection.writing: 1},
    perQuestionScores: {ExamSection.vocab: 0.5, ExamSection.reading: 2, ExamSection.cloze: 1, ExamSection.en2zh5: 2.5, ExamSection.writing: 15},
    vocab: [
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "I am leaving in ____ minute; in ____ fact, I'll leave when I turn off the lights.",
        text: "I am leaving in ____ minute; in ____ fact, I'll leave when I turn off the lights.",
        options: ["a; the", "/; /", "the; a", "a; /"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "Please turn to page ____, look at the ____ picture.",
        text: "Please turn to page ____, look at the ____ picture.",
        options: ["two; two", "two; second", "second; second", "second; two"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "The kids learned that light ____ faster than sound.",
        text: "The kids learned that light ____ faster than sound.",
        options: ["travel", "traveled", "travels", "has traveled"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "The photo exhibition was held to ____ the environmental awareness.",
        text: "The photo exhibition was held to ____ the environmental awareness.",
        options: ["rise", "give", "arise", "raise"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "The greatest lawyer made a speech ____ education law.",
        text: "The greatest lawyer made a speech ____ education law.",
        options: ["in", "on", "at", "for"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "—We need a drink. —____! Let's have one.",
        text: "—We need a drink. —____! Let's have one.",
        options: ["Greatly", "Simply", "Possibly", "Exactly"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "Neither you nor I am expert on this issue, ____?",
        text: "Neither you nor I am expert on this issue, ____?",
        options: ["are we", "aren't we", "do we", "don't we"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "The hall was named after the professor ____ made great contributions to the university.",
        text: "The hall was named after the professor ____ made great contributions to the university.",
        options: ["which", "who", "whose", "whom"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "Hardly had I put down my cell phone ____ it ran again.",
        text: "Hardly had I put down my cell phone ____ it ran again.",
        options: ["as", "than", "after", "when"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "Peter won the first prize of the speech competition, and he ____ have studied very hard.",
        text: "Peter won the first prize of the speech competition, and he ____ have studied very hard.",
        options: ["may", "must", "should", "could"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "The AI engineer, as well as his team members, ____ to attend the seminar on ChatGPT last month.",
        text: "The AI engineer, as well as his team members, ____ to attend the seminar on ChatGPT last month.",
        options: ["was invited", "were invited", "have been invited", "has been invited"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "The teacher explained it again ____ he could make himself better understood.",
        text: "The teacher explained it again ____ he could make himself better understood.",
        options: ["now that", "such that", "so that", "in that"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "The ____ of blood always makes him frightened.",
        text: "The ____ of blood always makes him frightened.",
        options: ["sight", "view", "look", "glance"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "As we arrived too early, ____ of the rooms were ready.",
        text: "As we arrived too early, ____ of the rooms were ready.",
        options: ["all", "none", "any", "both"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "When he was a child, the scientist was ____ about how life on earth began.",
        text: "When he was a child, the scientist was ____ about how life on earth began.",
        options: ["curious", "anxious", "careful", "hopeful"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "—Have you completed your report yet? —No, but I ____ on it all day yesterday.",
        text: "—Have you completed your report yet? —No, but I ____ on it all day yesterday.",
        options: ["would work", "had worked", "have worked", "was working"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "____ I know, they will go to Chengdu to watch the World University Games this summer.",
        text: "____ I know, they will go to Chengdu to watch the World University Games this summer.",
        options: ["Even though", "Even if", "As soon as", "As far as"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "Never in my life ____ such a wonderful lion dance.",
        text: "Never in my life ____ such a wonderful lion dance.",
        options: ["have I seen", "I have seen", "did I see", "I saw"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "The school ____ great importance to students' mental health.",
        text: "The school ____ great importance to students' mental health.",
        options: ["attaches", "takes", "pays", "offers"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "They were ____ in the middle of their telephone conversation.",
        text: "They were ____ in the middle of their telephone conversation.",
        options: ["cut away", "cut up", "cut down", "cut off"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "____ it was only 5 p.m., the street lights in this northeast city were already on.",
        text: "____ it was only 5 p.m., the street lights in this northeast city were already on.",
        options: ["Although", "However", "Since", "For"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "They gave a(n) ____ broadcast while the talent show was going on.",
        text: "They gave a(n) ____ broadcast while the talent show was going on.",
        options: ["living", "live", "alive", "lively"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "Lily has made an ____ to meet his science teacher next Monday.",
        text: "Lily has made an ____ to meet his science teacher next Monday.",
        options: ["attention", "approval", "agreement", "appointment"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "It's high time you ____ smoking.",
        text: "It's high time you ____ smoking.",
        options: ["give up", "gave up", "must give up", "will give up"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "Weather ____, they'll go to visit the Panda Base.",
        text: "Weather ____, they'll go to visit the Panda Base.",
        options: ["permits", "permitted", "permitting", "is permitting"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "The manager had assistant ____ a presentation for the meeting with the clients.",
        text: "The manager had assistant ____ a presentation for the meeting with the clients.",
        options: ["preparing", "to prepare", "prepared", "prepare"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "____ see the lost cat will get a gift as a reward.",
        text: "____ see the lost cat will get a gift as a reward.",
        options: ["Whomever", "No matter whom", "Whoever", "No matter who"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "We were excited to learn Prof. Tu Youyou became the ____ scientist who won the Nobel Prize.",
        text: "We were excited to learn Prof. Tu Youyou became the ____ scientist who won the Nobel Prize.",
        options: ["Chinese first woman", "first Chinese woman", "Chinese woman first", "first woman Chinese"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "I'd like to take ____ of this opportunity to thank you for your support.",
        text: "I'd like to take ____ of this opportunity to thank you for your support.",
        options: ["risk", "care", "advantage", "notice"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "Travelling is becoming ____ popular in China as more and more people have their own cars.",
        text: "Travelling is becoming ____ popular in China as more and more people have their own cars.",
        options: ["importantly", "successfully", "increasingly", "mostly"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
    ],
    readings: [
      Question(
        type: QType.reading,
        level: 'zsb',
        text: '阅读理解',
        passage: "While our world may be more interconnected than ever, families are still eager for opportunities to spend time together. Today grandparents are discovering a simple solution to connect with their grandchildren — to experience the magic of Walt Disney World Resort!\n\nWhether you're sharing your favorites from past trips, or creating new memories together during your first trip, adventure awaits. Be prepared for adventure and ride the family coaster Seven Dwarfs Mine Train Attraction in Fantasyland Area at Magic Kingdom Park. Don't miss the Disney Festival of Fantasy Parade, and, of course, It's a Small World Attraction. The Wishes Nighttime Spectacular show, Pirates of the Caribbean Attraction, and the classic Haunted Mansion Attraction are other musts.\n\nEpcot World Showcase is the place for families to explore 11 countries, and Disney's Animal Kingdom Theme Park offers the Kilimanjaro Safari Expedition. And the Festival of the Lion King Show. And in Toy Story Mania Attraction in Disney's Hollywood Studios, grandparents can compete against grandchildren in friendly games.\n\nIntroduce your grandkids to your favorite theme park at the Walt Disney World Resort. Visit Disneyworld.com/grandadventure to plan your next visit.",
        questions: [
          ReadingSubQ(
            question: "What does paragraph 1 focus on?",
            options: ["Parents and children need to spend more time together.", "The world we are living in is more interconnected than before.", "Going to Disneyland is an easy way to connect with family members.", "Grandparents are discovering a simple solution to their health problem."],
            answerIdx: -1,
          ),
          ReadingSubQ(
            question: "How is paragraph 2 mainly developed?",
            options: ["By telling stories", "By asking questions", "By making comparisons", "By giving examples"],
            answerIdx: -1,
          ),
          ReadingSubQ(
            question: "Where can grandparents and grandkids compete in friendly games?",
            options: ["In Magic Kingdom Park.", "In Toy Story Mania Attraction.", "In Animal Kingdom Theme Park.", "In Pirates of the Caribbean Attraction."],
            answerIdx: -1,
          ),
          ReadingSubQ(
            question: "When planning your next visit to Disneyland, you are advised to ____.",
            options: ["ask your grandkids for advice", "find experience from past trips", "visit the recommended website", "let others introduce their favorites"],
            answerIdx: -1,
          ),
          ReadingSubQ(
            question: "This text is most likely a(n) ____.",
            options: ["advertisement", "invitation", "speech", "lecture"],
            answerIdx: -1,
          ),
        ],
      ),
      Question(
        type: QType.reading,
        level: 'zsb',
        text: '阅读理解',
        passage: "Deng Qingming, 56, said that he never lost sight of his \"space dream\" while waiting, training and preparing for almost a quarter of a century to take part in a space mission.\n\nDeng, the last serving member of China's first group of astronauts to take part in a spaceflight, said that he never doubted his choice or considered quitting. Deng said that he had \"quietly prepared\" throughout his life for an opportunity to take part in a mission, adding, \"I don't allow myself to be unprepared in case that, one day, I would be called up.\"\n\n\"When I was told that I had been chosen for the Shenzhou XV mission, I was pretty calm. What I was thinking about at that time was that I must cherish this opportunity and train harder to honor their trust and my commitment.\"\n\nDeng said his gratitude goes to a lot of people, especially the scientists, engineers and other workers in China's space industry, because it had been those people who worked hard to send astronauts like him into space.\n\nAfter the news about Deng being selected as a member of the Shenzhou XV crew was published on Monday morning, many microbloggers congratulated him and said they were very happy that he could eventually realize his dream.",
        questions: [
          ReadingSubQ(
            question: "How long had Deng prepared for the space mission?",
            options: ["Nearly 56 years", "Nearly 25 years", "Nearly 16 years", "Nearly 15 years"],
            answerIdx: -1,
          ),
          ReadingSubQ(
            question: "The underlined word \"cherish\" in paragraph 3 is closest in meaning to ____.",
            options: ["Value", "Chase", "Verify", "Challenge"],
            answerIdx: -1,
          ),
          ReadingSubQ(
            question: "Who was Deng especially grateful to?",
            options: ["The people who chose him for the mission", "Those working in China's space industry", "Members of the Shenzhou XV crew", "China's first group of astronauts"],
            answerIdx: -1,
          ),
          ReadingSubQ(
            question: "Which of the following can best describe Deng?",
            options: ["Generous", "Humorous", "Intelligent", "Persistent"],
            answerIdx: -1,
          ),
          ReadingSubQ(
            question: "The text is mainly about ____.",
            options: ["An engineer who kept working hard", "A reporter who interviewed a veteran", "A scientist who took part in a space mission", "An astronaut who eventually realized his dream"],
            answerIdx: -1,
          ),
        ],
      ),
      Question(
        type: QType.reading,
        level: 'zsb',
        text: '阅读理解',
        passage: "China's traditional tea-making was added on Tuesday to the intangible cultural heritage list of the United Nations Educational, Scientific, and Cultural Organization (联合国教科文组织).\n\nThe item \"traditional tea processing techniques and associated social practices in China\" passed the 17th session of the UNESCO Intergovernmental Committee for the Safeguarding of the Intangible Cultural Heritage ongoing here in the Moroccan capital. China now has 43 items on the intangible cultural heritage list, continuing to be the most enlisted country in the world.\n\nWang Yongjian, head of the Chinese delegation to the UNESCO session, told Xinhua News Agency that the enlistment will make this cultural heritage more visible to the public and help promote respect for cultural differences and human creativity.\n\nThe traditional tea processing techniques and associated social practices in China consist of knowledge, skills and practices concerning the management of tea plantations, picking of tea leaves, manual processing, drinking, and sharing of tea.\n\nSince ancient times, Chinese people have been planting, picking, making and drinking tea. Tea producers have developed six types of tea: green, yellow, dark, white, oolong and black teas. Together with reprocessed teas such as flower-scented teas, there are over 2,000 tea products in China. Tea is ubiquitous in Chinese people's daily life as tea is served in families, workplaces and tea houses, to name a few.",
        questions: [
          ReadingSubQ(
            question: "Where did China's traditional tea-making pass the enlistment examination?",
            options: ["In China", "In the UN headquarters", "In the United States", "In the Morocco capital"],
            answerIdx: -1,
          ),
          ReadingSubQ(
            question: "According to Wang Yongjian, the enlistment will ____.",
            options: ["help promote the respect for different people", "help promote the creation of more tea products", "get more people to know about this cultural heritage", "get more people to show respect for the Chinese delegation"],
            answerIdx: -1,
          ),
          ReadingSubQ(
            question: "The underlined word \"ubiquitous\" in paragraph 5 is closest in meaning to ____.",
            options: ["quite common", "quite unique", "very delicious", "very precious"],
            answerIdx: -1,
          ),
          ReadingSubQ(
            question: "What can we learn from the text?",
            options: ["Chinese people usually do not drink tea at workplaces.", "There are more than two thousand types of tea in China.", "China now has the most intangible cultural heritage items enlisted by UNESCO.", "China's traditional tea-making consists merely of manual processing and sharing of tea."],
            answerIdx: -1,
          ),
          ReadingSubQ(
            question: "Which section of a newspaper may this text appear?",
            options: ["Sports", "Culture", "Science", "Education"],
            answerIdx: -1,
          ),
        ],
      ),
      Question(
        type: QType.reading,
        level: 'zsb',
        text: '阅读理解',
        passage: "People using happy emojis might seem cheerful — but are they really happy? Researchers from the University of Tokyo wanted to investigate whether \"display rules\" socially appropriate facial expressions in a given situation existed in communications with emojis. The study saw about 1,289 volunteers from Japan using emojis in response to online conversations. The participants, most of whom were female and aged 11 to 26 years, self-reported the intensity of emotional expressions.\n\nResults suggested that happy emojis were often used to make negative emotions and \"manage the expression to make a message seem more positive.\" Negative emojis such as any of the sad face emojis were only used when the participants felt very strong negative feelings.\n\nExperts found that people were most likely to use positive emojis when they were feeling negative emotions or when talking to people of higher status, but they were also less likely to express emotions through emojis toward this group of people. People were more likely to use accurate emojis to express their feelings when talking to close friends.\n\n\"As online socializing becomes more popular, people have become accustomed to modifying their expressions and examining the appropriateness of their communication,\" Moyu Liu, an emotional behavior expert at the University of Tokyo who led the research said. \"However, I realized that this may lead us to lose touch with our real emotions.\"",
        questions: [
          ReadingSubQ(
            question: "What did researchers from the University of Tokyo want to find out?",
            options: ["How to use emojis to express our emotions properly", "When to make facial expressions socially appropriate", "If the display rules of facial expressions existed in communicating with emojis", "Whether happy emojis were used to mask negative emotions in communications"],
            answerIdx: -1,
          ),
          ReadingSubQ(
            question: "What do we know about the participants of the research?",
            options: ["They were mostly female.", "They were in their early twenties.", "They were asked to report their use of emojis.", "They were selected from the University of Tokyo."],
            answerIdx: -1,
          ),
          ReadingSubQ(
            question: "When the participants had very strong negative emotions, they ____.",
            options: ["used happy emojis", "masked their feelings", "modified their responses", "chose negative emojis"],
            answerIdx: -1,
          ),
          ReadingSubQ(
            question: "People were more likely to use accurate emojis when ____.",
            options: ["they felt a little sad", "they chatted with close friends", "they needed to make a message more positive", "they communicated with people of higher status"],
            answerIdx: -1,
          ),
          ReadingSubQ(
            question: "According to Moyu Liu, what might be the negative influence of this trend?",
            options: ["We will be out of touch with our real friends.", "We will fail to manage our facial expressions.", "We will spend too much time socializing online.", "We will lose the ability to express our true feelings."],
            answerIdx: -1,
          ),
        ],
      ),
    ],
    cloze: [
      Question(
        type: QType.cloze,
        level: 'zsb',
        passage: "A young woman born after 1995 living in Suzhou, East China's Jiangsu Province, recently ____51____ more than 1000 yuan a month by ____52____ a part-time job as a dog walker.\n\nThe girl, surnamed Wei, explained, \"The work is relatively ____53____ , I just need to take the dog out for a walk. Sometimes, the owner may ask to see their dog's droppings to ____54____ if the dog is sick or not.\" ____55____ surfing the Internet, Wei ran across some people who were ____56____ busy at work to walk their dogs and posted some ____57____ looking for hired help.\n\nSince Wei has relatively few working hours at her ____58____ job and has experience raising dogs herself, she began to ____59____ her information ____60____ social media platforms and decided to take up a part-time job ____61____ a dog walker. ____62____ 30 yuan for half an hour, Wei can earn 1000 to 2000 yuan a month. When asked why she ____63____ the job, Wei said she loves dogs very much and ____64____ playing with them while walking them. \"All the dogs are very cute and have a good ____65____ ,\" Wei said. \"They ____66____ my day.\"\n\nMany netizens said Wei's part-time job was their ____67____ job. \"Where can I find such a good job? I can do it for 15 yuan,\" one netizen ____68____ . \"A lot of people love dogs, ____69____ sometimes they just don't have time to walk or play with their dogs. It's great to have a job that ____70____ everyone,\" another netizen commented.\n\n第二部分  非选择题",
        text: '完形填空',
      ),
    ],
    clozeSubs: [
      ClozeSubQ(
        blankIdx: 51,
        sentence: "A young woman born after 1995 living in Suzhou, East China's Jiangsu Province, recently 51 more than 1000 yuan a month by 52 a part-time job as a dog walker.",
        options: ["found", "saved", "spent", "earned"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 52,
        sentence: "A young woman born after 1995 living in Suzhou, East China's Jiangsu Province, recently 51 more than 1000 yuan a month by 52 a part-time job as a dog walker.",
        options: ["taking", "making", "creating", "utilizing"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 53,
        sentence: "The girl, surnamed Wei, explained, \"The work is relatively 53 , I just need to take the dog out for a walk.",
        options: ["busy", "difficult", "simple", "different"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 54,
        sentence: "Sometimes, the owner may ask to see their dog's droppings to 54 if the dog is sick or not.\"",
        options: ["test", "research", "detect", "determine"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 55,
        sentence: "",
        options: ["Although", "While", "After", "Before"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 56,
        sentence: "55 surfing the Internet, Wei ran across some people who were 56 busy at work to walk their dogs and posted some 57 looking for hired help.",
        options: ["very", "too", "so", "quite"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 57,
        sentence: "55 surfing the Internet, Wei ran across some people who were 56 busy at work to walk their dogs and posted some 57 looking for hired help.",
        options: ["news", "notes", "messages", "notices"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 58,
        sentence: "Since Wei has relatively few working hours at her 58 job and has experience raising dogs herself, she began to 59 her information 60 social media platforms and decided to take up a part-time job 61 a dog walker.",
        options: ["regular", "main", "temporary", "common"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 59,
        sentence: "Since Wei has relatively few working hours at her 58 job and has experience raising dogs herself, she began to 59 her information 60 social media platforms and decided to take up a part-time job 61 a dog walker.",
        options: ["copy", "print", "send", "post"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 60,
        sentence: "Since Wei has relatively few working hours at her 58 job and has experience raising dogs herself, she began to 59 her information 60 social media platforms and decided to take up a part-time job 61 a dog walker.",
        options: ["in", "on", "by", "from"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 61,
        sentence: "Since Wei has relatively few working hours at her 58 job and has experience raising dogs herself, she began to 59 her information 60 social media platforms and decided to take up a part-time job 61 a dog walker.",
        options: ["as", "for", "with", "like"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 62,
        sentence: "",
        options: ["Demanding", "Paying", "Charging", "Pricing"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 63,
        sentence: "When asked why she 63 the job, Wei said she loves dogs very much and 64 playing with them while walking them.",
        options: ["lost", "chose", "quite", "go"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 64,
        sentence: "When asked why she 63 the job, Wei said she loves dogs very much and 64 playing with them while walking them.",
        options: ["allows", "practices", "tries", "enjoys"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 65,
        sentence: "\"All the dogs are very cute and have a good 65 ,\" Wei said.",
        options: ["hobby", "meal", "temper", "future"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 66,
        sentence: "\"They 66 my day.\"",
        options: ["create", "make", "influence", "develop"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 67,
        sentence: "Many netizens said Wei's part-time job was their 67 job.",
        options: ["dream", "routine", "present", "past"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 68,
        sentence: "I can do it for 15 yuan,\" one netizen 68 .",
        options: ["suggest", "mentioned", "joked", "bargained"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 69,
        sentence: "\"A lot of people love dogs, 69 sometimes they just don't have time to walk or play with their dogs.",
        options: ["and", "so", "but", "because"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 70,
        sentence: "It's great to have a job that 70 everyone,\" another netizen commented.",
        options: ["benefits", "motivates", "serves", "stimulates"],
        answerIdx: -1,
      ),
    ],
    en2zh5: En2zh5Entry(
      sentences: [
        "While our world may be more interconnected than ever, families are still eager for opportunities to spend time together.",
        "When I was told that I had been chosen for the Shenzhou XV mission, I was pretty calm.",
        "Since ancient times, Chinese people have been planting, picking, making and drinking tea.",
        "People using happy emojis might seem cheerful -- but are they really happy?",
      ],
    ),
    writing: WritingEntry(
      topic: "你叫李夏，你要邀请你的外教史密斯教授参加你们班4月22日以\"世界地球日\"为主题的登山活动。请给他写一封邀请信。内容包括：1. 活动目的；2. 活动时间和地点；3. 注意事项。\n1. 词数100词左右。\n2. 可以适当增加细节，使行文流畅。\n3. 文章开头已为你写好，不计入总词数。\n参考词汇：the World Earth Day; mountain climbing; environment\nDear Prof. Smith,\nHow are you?",
    ),
  );
}

FullExamPaper _buildPaper2024() {
  return FullExamPaper(
    title: '四川专升本大学英语 2024 年真题',
    totalTimeMin: 120,
    isRealPaper: true,
    realYear: '2024',
    sectionCounts: {ExamSection.vocab: 20, ExamSection.reading: 16, ExamSection.cloze: 20, ExamSection.dialogue: 5, ExamSection.bankedCloze: 10, ExamSection.en2zh5: 5, ExamSection.writing: 1},
    perQuestionScores: {ExamSection.vocab: 1, ExamSection.reading: 2.5, ExamSection.cloze: 1.5, ExamSection.dialogue: 2, ExamSection.bankedCloze: 1, ExamSection.en2zh5: 3, ExamSection.writing: 25},
    vocab: [
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "Chengdu is ____ beautiful city and ____ capital of Sichuan Province.",
        text: "Chengdu is ____ beautiful city and ____ capital of Sichuan Province.",
        options: ["a; a", "a; the", "the; the", "the; a"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "They ____ be at home, for there is no light in the room.",
        text: "They ____ be at home, for there is no light in the room.",
        options: ["can't", "mustn't", "needn't", "shouldn't"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "The new movie directed by Jia Ling is quite inspiring, ____?",
        text: "The new movie directed by Jia Ling is quite inspiring, ____?",
        options: ["isn't it", "is it", "did she", "didn't she"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "The professor, along with his assistants, ____ on the project day and night to meet the deadline.",
        text: "The professor, along with his assistants, ____ on the project day and night to meet the deadline.",
        options: ["work", "working", "is working", "are working"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "The president ordered that all exits ____ kept clear in case of fire.",
        text: "The president ordered that all exits ____ kept clear in case of fire.",
        options: ["are", "were", "would be", "should be"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "I'd like to study civil engineering in university, ____ my cousin prefers computer science.",
        text: "I'd like to study civil engineering in university, ____ my cousin prefers computer science.",
        options: ["though", "as", "while", "for"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "A college in Sichuan announced a spring break yesterday, ____ caused a heated discussion among students.",
        text: "A college in Sichuan announced a spring break yesterday, ____ caused a heated discussion among students.",
        options: ["what", "which", "as", "that"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "News comes ____ video can be easily made with the AI tool.",
        text: "News comes ____ video can be easily made with the AI tool.",
        options: ["when", "which", "because", "that"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "Tracy appreciated ____ the opportunity to visit China through the summer camp program.",
        text: "Tracy appreciated ____ the opportunity to visit China through the summer camp program.",
        options: ["having been given", "having given", "to have been given", "to have given"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "Jack has been living in Beijing for years, ____, he speaks Chinese quite fluently.",
        text: "Jack has been living in Beijing for years, ____, he speaks Chinese quite fluently.",
        options: ["however", "otherwise", "therefore", "though"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "It is necessary to look into the case ____ you take any action.",
        text: "It is necessary to look into the case ____ you take any action.",
        options: ["before", "though", "unless", "because"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "I can't thank you ____ much for your help. Without it, I couldn't have completed this task on time.",
        text: "I can't thank you ____ much for your help. Without it, I couldn't have completed this task on time.",
        options: ["very", "too", "quite", "so"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "A good team leader has to know the ____ and weakness of the member and create a harmonious environment for work.",
        text: "A good team leader has to know the ____ and weakness of the member and create a harmonious environment for work.",
        options: ["benefits", "strengths", "interests", "skills"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "—Volunteering is becoming ____ popular in China. —Yeah, people are now aware that helping others is helping themselves.",
        text: "—Volunteering is becoming ____ popular in China. —Yeah, people are now aware that helping others is helping themselves.",
        options: ["increasingly", "naturally", "consequently", "successfully"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "What's the ____ of helping him if he does not want to make any effort himself?",
        text: "What's the ____ of helping him if he does not want to make any effort himself?",
        options: ["chance", "theme", "object", "point"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
    ],
    cloze: [
      Question(
        type: QType.cloze,
        level: 'zsb',
        passage: "The Silk Road is a name given to the many trade routes that connected Europe and the Mediterranean (地中海) with the Asian world. The route is over 6,500 km long and got its name because the early Chinese traded silk along it. Although silk was the main trading item, there were many other goods that travelled along the Silk Road between Eastern Asia and Europe. In the course of time, medicine, perfumes, spices and livestock (家畜) found their way between continents.\n\nThe Chinese learned to make silk thousands of years ago. For a long time they were the only ones who knew how to make this precious material. Only the emperor, his family and his highest advisers were allowed to wear clothes made of silk. For a long time the Chinese guarded this secret very carefully. The ancient Romans were the first Europeans who became aware of this wonderful material. Trading started, often with Indians as middlemen (中间人) who traded silk with the Chinese in exchange for gold and silver which they got from the Romans.\n\nTravelling along the route was dangerous. The hot desert, high mountains and sandstorms made traveling a rough business. Most of the goods along the Silk Road were carried by caravans (商队). Traders sometimes brought goods from one destination on the Silk Road to another, from where the goods would be transported by someone else. Over the centuries people settled along the ancient route and many cities emerged. Later on there were fewer hardships to overcome, but by no means was it easy.\n\nIn the early Middle Ages, traffic along the route decreased because of the decline of the Roman Empire. Trading along the Silk Road became stronger again between the 13th and 14th centuries, when the Mongols controlled central Asia. During the Age of Exploration the Silk Road lost its importance because new sea routes to Asia were discovered.",
        text: '完形填空',
      ),
    ],
    writing: WritingEntry(
      topic: "假如你是学生会主席李夏，下周\"国际交流周\"学校将要举办一个国际交流会，现请你给外教Smith教授写一封电子邮件，邀请他出席开幕式并参加这场活动。内容要点包括：\n1. 活动时间、地点；\n2. 活动简介和注意事项。\n参考词汇：International Exchange Week; opening ceremony; invitation\nDear Prof. Smith,",
    ),
  );
}

FullExamPaper _buildPaper2025() {
  return FullExamPaper(
    title: '四川专升本大学英语 2025 年真题',
    totalTimeMin: 120,
    isRealPaper: true,
    realYear: '2025',
    sectionCounts: {ExamSection.vocab: 20, ExamSection.reading: 16, ExamSection.cloze: 20, ExamSection.dialogue: 5, ExamSection.bankedCloze: 10, ExamSection.en2zh5: 5, ExamSection.writing: 1},
    perQuestionScores: {ExamSection.vocab: 1, ExamSection.reading: 2.5, ExamSection.cloze: 1.5, ExamSection.dialogue: 2, ExamSection.bankedCloze: 1, ExamSection.en2zh5: 3, ExamSection.writing: 25},
    vocab: [
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "Henry likes to play ____ piano, while his brother prefers playing ____ football.",
        text: "Henry likes to play ____ piano, while his brother prefers playing ____ football.",
        options: ["the; the", "a; a", "the; /", "/; the"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "We invited Linda and Cathy to dinner, but ____ of them came.",
        text: "We invited Linda and Cathy to dinner, but ____ of them came.",
        options: ["both", "none", "neither", "all"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "The number of new energy vehicles in our country ____ a lot in recent years.",
        text: "The number of new energy vehicles in our country ____ a lot in recent years.",
        options: ["increases", "increased", "has increased", "have increased"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "—Juicy graduated from college at a very young age. —She ____ have been a smart student.",
        text: "—Juicy graduated from college at a very young age. —She ____ have been a smart student.",
        options: ["can", "must", "should", "might"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "She wondered what effective measures ____ to increase the productivity.",
        text: "She wondered what effective measures ____ to increase the productivity.",
        options: ["will take", "would take", "will be taken", "would be taken"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "—Have you ever been to Beijing? —No, I wish I ____.",
        text: "—Have you ever been to Beijing? —No, I wish I ____.",
        options: ["have", "will", "do", "had"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
    ],
  );
}

FullExamPaper _buildPaper2026() {
  return FullExamPaper(
    title: '四川专升本大学英语 2026 年真题',
    totalTimeMin: 120,
    isRealPaper: true,
    realYear: '2026',
    sectionCounts: {ExamSection.vocab: 20, ExamSection.reading: 14, ExamSection.cloze: 20, ExamSection.dialogue: 5, ExamSection.bankedCloze: 10, ExamSection.en2zh5: 5, ExamSection.writing: 1},
    perQuestionScores: {ExamSection.vocab: 1, ExamSection.reading: 2.5, ExamSection.cloze: 1.5, ExamSection.dialogue: 2, ExamSection.bankedCloze: 1, ExamSection.en2zh5: 3, ExamSection.writing: 25},
    vocab: [
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "The price of petrol has become ____ major concern of ____ society.",
        text: "The price of petrol has become ____ major concern of ____ society.",
        options: ["/; a", "the; a", "the; /", "a; /"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "Could you please tell me ____ we get to the Sanxingdui Museum?",
        text: "Could you please tell me ____ we get to the Sanxingdui Museum?",
        options: ["what", "which", "how", "where"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "Jack, as well as his two children, ____ for China this afternoon.",
        text: "Jack, as well as his two children, ____ for China this afternoon.",
        options: ["are to leave", "leaves", "is leaving", "leave"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "Chengdu, ____ for its rich cultural heritage and delicious local food, has become a top choice for travelers around the world.",
        text: "Chengdu, ____ for its rich cultural heritage and delicious local food, has become a top choice for travelers around the world.",
        options: ["knowing", "known", "to know", "to be known"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "—Peter had a wonderful party yesterday. —____.",
        text: "—Peter had a wonderful party yesterday. —____.",
        options: ["So did I", "So I did", "So I had", "So had I"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "The Dujiangyan Irrigation System is still in use ____ it was built over 2000 years ago.",
        text: "The Dujiangyan Irrigation System is still in use ____ it was built over 2000 years ago.",
        options: ["because", "though", "if", "since"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "A lot of progress has been made in the 14th ____ Plan period.",
        text: "A lot of progress has been made in the 14th ____ Plan period.",
        options: ["Five-year", "Five years", "Fifth-year", "Fifth years"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "The new washing machine uses ____ water and electricity than the old one.",
        text: "The new washing machine uses ____ water and electricity than the old one.",
        options: ["little", "less", "few", "fewer"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "Many people find ____ enjoyable to travel in western Sichuan.",
        text: "Many people find ____ enjoyable to travel in western Sichuan.",
        options: ["this", "that", "it", "what"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "—The last man ____ pays for the meal. —Good idea!",
        text: "—The last man ____ pays for the meal. —Good idea!",
        options: ["arrived", "arrives", "to arrive", "arriving"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "The Giant Panda Base ____ we visited last week is popular with foreign tourists.",
        text: "The Giant Panda Base ____ we visited last week is popular with foreign tourists.",
        options: ["which", "that", "where", "when"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "He never said he was good at singing, ____?",
        text: "He never said he was good at singing, ____?",
        options: ["was he", "wasn't he", "didn't he", "did he"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "The teacher said practice ____ perfect, so we should keep working hard.",
        text: "The teacher said practice ____ perfect, so we should keep working hard.",
        options: ["makes", "made", "will make", "has made"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "He couldn't fall asleep with all that noise ____.",
        text: "He couldn't fall asleep with all that noise ____.",
        options: ["going on", "goes on", "went on", "to go on"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "It is necessary that measures ____ to further develop vocational education.",
        text: "It is necessary that measures ____ to further develop vocational education.",
        options: ["must be taken", "be taken", "are taken", "will be taken"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "Vivian has a lot of problems with her life, but she does not know whom to ____.",
        text: "Vivian has a lot of problems with her life, but she does not know whom to ____.",
        options: ["look for", "turn to", "deal with", "talk about"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "It is very ____ of you to help me with Chinese learning.",
        text: "It is very ____ of you to help me with Chinese learning.",
        options: ["polite", "careful", "kind", "wise"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "You ____ finish the project before the deadline, or you will face serious consequences.",
        text: "You ____ finish the project before the deadline, or you will face serious consequences.",
        options: ["must", "may", "can", "would"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "Carelessness was the main ____ of the accident in the lab.",
        text: "Carelessness was the main ____ of the accident in the lab.",
        options: ["result", "cause", "warning", "reflection"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
      Question(
        type: QType.choice,
        level: 'zsb',
        question: "If it rains tomorrow, we will ____ the sports meeting till next week.",
        text: "If it rains tomorrow, we will ____ the sports meeting till next week.",
        options: ["put up", "put on", "put off", "put in"],
        answerIdx: -1,
        knowledge: ['真题'],
      ),
    ],
    readings: [
      Question(
        type: QType.reading,
        level: 'zsb',
        text: '阅读理解',
        passage: "If Tom Henderson were a poet, he might propose to his longtime girlfriend, Steph Cater, by writing an ode to her eyes. But Henderson is a farmer in New South Wales, Australia, so he proposed in a way only a love-struck farmer could.\n\nIt took five months to plant, grow, shape, weed and struggle over a special canola crop. Once it had bloomed in early September, Henderson and Cater, a teacher, boarded a small plane at his invitation. She was expecting a flyover of some farmland, an activity she'd enjoyed in the past. But as they flew above the crops, rather than alfalfa or corn, she saw a field of bright yellow arranged in letters that were roughly 40 feet tall. All together it read \"Will You Marry Me?\"\n\n\"I thought that he'd propose soon,\" Cater told the Australian Broadcasting Corp.\n\n\"But I wasn't expecting him to do it the way that he did.\"\n\nCater didn't need months of planning, shaping and struggling over her response. It was quick and to the point: \"Yes.\"",
        questions: [
          ReadingSubQ(
            question: "Steph Carter is a ____.",
            options: ["poet", "pilot", "teacher", "reporter"],
            answerIdx: -1,
          ),
          ReadingSubQ(
            question: "Tom Henderson's proposal words \"Will You Marry Me\" were ____.",
            options: ["broadcast on the radio", "written in a love poem", "painted on a small plane", "arranged in the farm field"],
            answerIdx: -1,
          ),
          ReadingSubQ(
            question: "Tom Henderson's girlfriend accepted his proposal ____.",
            options: ["five months later", "in a struggle", "without hesitation", "after careful planning"],
            answerIdx: -1,
          ),
          ReadingSubQ(
            question: "What do we know from the text?",
            options: ["Tom Henderson loves his girlfriend very much.", "Tom Henderson bought a plane for his girlfriend.", "Steph Carter enjoyed working on the farm in the past.", "Steph Carter works for the Australian Broadcasting Corp."],
            answerIdx: -1,
          ),
        ],
      ),
      Question(
        type: QType.reading,
        level: 'zsb',
        text: '阅读理解',
        passage: "Last summer, I got my first part-time job in a small café near my neighborhood. I was both excited and nervous because it was my first time working and interacting with strangers in a professional setting.\n\nOn my first day, my manager, Mia, showed me around and taught me how to make coffee, serve customers, and handle the cash register. She was very patient and encouraging, which helped calm my nerves. I started with simple tasks like cleaning tables and taking orders, but gradually, I learned to make various coffee drinks.\n\nOne of the biggest challenges was dealing with difficult customers. I remember one afternoon, a customer was upset because his coffee was not hot enough. I apologized sincerely and offered to make a new one for him. After he received the new coffee, he smiled and thanked me for my service.\n\nAs time went by, I, a teenager named Bob, got better and better at my job. I could handle peak hours smoothly and make perfect coffee without Mia's help. Regular customers often noticed my huge progress and praised my skills. It made my day. Through this wonderful experience, I earned my own pocket money and greatly boosted my confidence.",
        questions: [
          ReadingSubQ(
            question: "Which word best describes Mia?",
            options: ["strict", "critical", "helpful", "confident"],
            answerIdx: -1,
          ),
          ReadingSubQ(
            question: "What is the main idea of the fourth paragraph?",
            options: ["Bob offered outgoing service.", "Bob got better at his job.", "Bob earned his pocket money.", "Bob praised regular customers."],
            answerIdx: -1,
          ),
        ],
      ),
      Question(
        type: QType.reading,
        level: 'zsb',
        text: '阅读理解',
        passage: "The Chinese company AutoFlight, founded in 2017, developed the Matrix, which can carry up to 10 passengers. It has a 20-meter wingspan, and is 17.1 meters long and 3.3 meters tall. It can travel for about an hour without charging.\n\nStaff moved the Matrix from the hangar to a helipad. The eVTOL was ready: the propellers were turned on, and after a few minutes of checks to ensure everything was working, it began rising. It was noisy, but less so than a helicopter. Around 10 minutes later, and after two laps around the heliport, the Matrix returned and landed smoothly with no problems.\n\nOn a recent chilly afternoon, AutoFlight conducted a flying demonstration for the Associated Press at its low-altitude flight test facility. Staff moved the Matrix from a hangar to a helipad. The eVTOL was ready: the propellers were turned on. After a few minutes of checks, it began rising. It was noisy, but less so than a helicopter. Around 10 minutes later, after two laps around the heliport, the Matrix returned and landed smoothly with no problems.\n\nWhen would a flying taxi become a reality? \"A couple of years? This is a very good question, but this is very tough question for me to answer,\" said Steven Yang, senior vice president of AutoFlight. Yang said that AutoFlight hopes to get a type certificate from regulators by 2027, meaning that authorities would confirm that the aircraft's design meets safety standards. But other regulatory approvals would still be required for an operator certificate to carry passengers. The Matrix is still a prototype, and the company is working to refine its design and performance ahead of certification.",
        questions: [
          ReadingSubQ(
            question: "What do we know about Matrix?",
            options: ["It's a kind of taxi in Kunshan.", "It uses electricity as power.", "It's a company from China.", "It's the largest aircraft in the world."],
            answerIdx: -1,
          ),
          ReadingSubQ(
            question: "What is Paragraph 4 mainly about?",
            options: ["The future of the flying taxi.", "The safety standards of the Matrix.", "The expert's opinion on the flying taxi.", "The performance of the Matrix during the test."],
            answerIdx: -1,
          ),
          ReadingSubQ(
            question: "According to Steven Yang, the Matrix ____.",
            options: ["will be used directly without any improvement in the future", "is expected to carry passengers after the future related approvals", "has already received a type certificate from Chinese regulators", "has already got an operator certificate to fly commercially"],
            answerIdx: -1,
          ),
          ReadingSubQ(
            question: "In which column of a newspaper may this text appear?",
            options: ["Science", "Education", "Nature", "Culture"],
            answerIdx: -1,
          ),
        ],
      ),
    ],
    cloze: [
      Question(
        type: QType.cloze,
        level: 'zsb',
        passage: "Last summer, I went hiking with my father in the mountains. It was my first time, so I felt very ____37____ . I was afraid of the dark and all the ____38____ things in the mountains. ____39____ , my father kept encouraging me, and we finally agreed to go.\n\nBefore we left, we ____40____ our bags carefully. I ____41____ some water, snacks and a map in my bag. Then we started our ____42____ early in the morning. The path was very ____43____ and it became steeper soon. I wanted to ____44____ halfway. \"Dad, I really can't go on,\" I said in a low voice.\n\nMy father ____45____ at me gently. \"We have already come so far. How about keeping moving?\" I took his ____46____ and walked on step by step. Little by little, I ____47____ my fear.\n\nWhen we finally ____48____ the top, I was completely amazed. The ____49____ was so beautiful — green mountains, tall trees and clear blue sky. I truly thought it was ____50____ every difficulty.\n\nThat night, we ____51____ the tent and built a fire to keep warm. We ate roasted marshmallows and enjoyed the bright ____52____ in the sky. It was really a ____53____ night.\n\nBut bad luck ____54____ at midnight. It started to rain hard. The tent ____55____ and leaked water badly. Our sleeping bags became wet. I felt so ____56____ .\n\nMy father comforted me patiently. \"Life is not always full of sunshine. Sometimes there is rain, but we should never  57 .\"\n\nThe next morning, we went back home. This trip gave me a clear lesson: with courage and support, we can beat any difficulty in life.",
        text: '完形填空',
      ),
    ],
    clozeSubs: [
      ClozeSubQ(
        blankIdx: 37,
        sentence: "It was my first time, so I felt very 37 .",
        options: ["excited", "nervous", "happy", "surprised"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 38,
        sentence: "I was afraid of the dark and all the 38 things in the mountains.",
        options: ["easy", "comfortable", "strange", "wonderful"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 39,
        sentence: "",
        options: ["So", "However", "Or", "Unless"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 40,
        sentence: "Before we left, we 40 our bags carefully.",
        options: ["checked", "locked", "packed", "weighed"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 41,
        sentence: "I 41 some water, snacks and a map in my bag.",
        options: ["put", "left", "found", "threw"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 42,
        sentence: "Then we started our 42 early in the morning.",
        options: ["work", "business", "visit", "trip"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 43,
        sentence: "The path was very 43 and it became steeper soon.",
        options: ["wide", "smooth", "steep", "bright"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 44,
        sentence: "I wanted to 44 halfway.",
        options: ["give up", "turn up", "get up", "stand up"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 45,
        sentence: "My father 45 at me gently.",
        options: ["shouted", "laughed", "looked", "smiled"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 46,
        sentence: "How about keeping moving?\" I took his 46 and walked on step by step.",
        options: ["bag", "hand", "map", "coat"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 47,
        sentence: "Little by little, I 47 my fear.",
        options: ["met", "increased", "overcame", "shared"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 48,
        sentence: "When we finally 48 the top, I was completely amazed.",
        options: ["reached", "left", "found", "marked"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 49,
        sentence: "The 49 was so beautiful — green mountains, tall trees and clear blue sky.",
        options: ["view", "sign", "symbol", "park"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 50,
        sentence: "I truly thought it was 50 every difficulty.",
        options: ["similar", "worth", "busy", "difficult"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 51,
        sentence: "That night, we 51 the tent and built a fire to keep warm.",
        options: ["set up", "picked up", "took up", "turned up"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 52,
        sentence: "We ate roasted marshmallows and enjoyed the bright 52 in the sky.",
        options: ["clouds", "stars", "fires", "tents"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 53,
        sentence: "It was really a 53 night.",
        options: ["terrible", "meaningless", "memorable", "boring"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 54,
        sentence: "But bad luck 54 at midnight.",
        options: ["moved", "dried", "disappeared", "struck"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 55,
        sentence: "The tent 55 and leaked water badly.",
        options: ["interested", "relaxed", "disappointed", "excited"],
        answerIdx: -1,
      ),
      ClozeSubQ(
        blankIdx: 56,
        sentence: "I felt so 56 .",
        options: ["hurry up", "give up", "look up", "make up"],
        answerIdx: -1,
      ),
    ],
    dialogue: DialogueEntry(
      scenario: "人力资源部（HR）电话咨询求职与会员卡办理（2026真题）",
      dialogueLines: [
        "W: Good afternoon, Human Resources Department. ____57____",
        "M: Yes, please.  58  Could you tell me how to apply?",
        "W: Yes, of course. You just need to fill out a job application form and send it to us.",
        "M: Great.  59  My name is John and I live at 328 Saint Nick Street.",
        "W: OK. I'll send it to you right away.",
        "M: I'd also like to apply for a membership card for your department store.",
        "W: You'll have to speak to someone else about that. The number is...",
        "M:  60  Let me have a pen. OK, go ahead.",
        "W: 71-658-0091. ____61____",
        "M: Thank you very much.",
      ],
      options: [
        "Can I help you?",
        "Hold on a moment, please.",
        "I'll fill in the form right now.",
        "Please ask to speak to Charles.",
        "Can you send me a form?",
        "Please give me your phone number.",
        "I'm interested in working at your department store.",
      ],
      answerLetters: [
        '?',
        '?',
        '?',
        '?',
        '?',
      ],
    ),
    writing: WritingEntry(
      topic: "假设你是李华，请给即将进入大学的大一新生写一封信，话题开放，可围绕学习、生活、社交等方面给出建议。\n要求：词数不少于100词，格式正确，行文连贯。\nDear freshmen,",
    ),
  );
}
